model: "efficientnet_b0"
weight_decay: 1e-2
drop: 0.2
drop_path: 0.2
lr: 0.002
batch_size: 128
epochs: 400
sched: "cosine"
opt: "adamp"
workers: 8
warmup_lr: 1e-4
aa: "rand-m9-mstd0.5"
remode: "pixel"
reprob: 0.2
amp: true
bn_momentum: 0.1
mixup: 0.2
mixup-off-epoch: 400
model_ema: True
model_ema_decay: 0.9999
num_classes: 1000
img_size: 224